# Generated by Django 5.1.2 on 2024-11-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_productoadquirido_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoadquirido',
            name='fecha_adquisicion',
            field=models.DateField(),
        ),
    ]
