# Generated by Django 5.1.2 on 2024-11-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_productovendido_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoadquirido',
            name='iva',
            field=models.PositiveIntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='productovendido',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=4),
        ),
    ]
