# Generated by Django 5.1.2 on 2024-11-04 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('RESULTADO_DEUDOR', 'Cuentas de Resultado Deudoras'), ('RESULTADO_ACREEDOR', 'Cuentas de Resultado Acreedoras'), ('CIERRE', 'Cuenta de Cierre'), ('ORDEN', 'Cuentas de Orden')], max_length=50)),
                ('nivel', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='Contabilidad.cuenta')),
            ],
            options={
                'verbose_name_plural': 'Cuentas',
            },
        ),
    ]
