# Generated by Django 5.1.2 on 2024-11-05 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('RESULTADO_DEUDOR', 'Cuentas de Resultado Deudoras'), ('RESULTADO_ACREEDOR', 'Cuentas de Resultado Acreedoras'), ('CIERRE', 'Cuenta de Cierre'), ('ORDEN', 'Cuentas de Orden')], max_length=50)),
                ('nivel', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='Contabilidad.cuenta')),
            ],
            options={
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=1)),
                ('ano', models.PositiveIntegerField(default=2024)),
            ],
            options={
                'verbose_name_plural': 'Periodos',
                'unique_together': {('mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contabilidad.cuenta')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contabilidad.periodo')),
            ],
        ),
    ]
