# Generated by Django 5.1.2 on 2024-11-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESOS', 'Ingresos'), ('GASTOS', 'Gastos'), ('RESULTADO_DEUDOR', 'Cuentas de Resultado Deudoras'), ('RESULTADO_ACREEDOR', 'Cuentas de Resultado Acreedoras'), ('CIERRE', 'Cuenta de Cierre'), ('ORDEN', 'Cuentas de Orden')], max_length=50),
        ),
    ]
