# Generated by Django 5.1.2 on 2024-11-05 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0002_alter_cuenta_tipo'),
        ('Contabilidad', '0002_periodo_transaccion'),
    ]

    operations = [
    ]
