# Generated by Django 5.1.2 on 2024-11-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0003_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='monto',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='debe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='haber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
